### ISSUE TITLE
Current Meteor API for package exports

### ISSUE THREAD

**Issue by jdlubrano** [hyperborea/meteor-datamaps#1]
Hello,

I was interested in using your package, but I was curious about a few things:
- It doesn't look like your package uses the Meteor package API to export `Datamaps` as a global variable.  Yes, Datamap(s) is bound to the `window` object, but your approach may cause problems when other developers (like me) want to use your project as a dependency.  The typical [Meteor `api.imply`](http://docs.meteor.com/#/full/packagejs) calls do not work as intended with your package, for instance.
- Do you purposely exclude the US maps from your package?  I see that your `package.js` file only includes `datamaps/dist/datamaps.world.min.js`.  If that was your intent, that is perfectly reasonable...I was just curious why you had not chosen `datamaps/dist/datamaps.all.js`.

So, what I am really driving at is one of two possibilities.

Option one, would you be willing to accept pull requests that move your project closer to the current Meteor state-of-the-art?

Or would I be better served creating an official [MeteorPackaging](https://github.com/MeteorPackaging) repository (probably using [Meteor Autopublish](http://autopublish.meteor.com)).  I have been working with the folks who own the Meteor Packaging organization, and I think they have a pretty solid approach when it comes to packaging existing third-party libraries.

I am assuming that your package was originally created for your own use and if you have no interest in  making it easier to share `Datamaps` with a wider audience, I completely understand.  I just thought it would be worthwhile to see where you stood before I moved forward.

**Comment by hyperborea** [comment]
Thanks for reaching out to me, that's very considerate! The package was indeed built for an internal use case and hasn't got much love since. In an attempt to quickly address your main concerns I've just updated the package to a) export Datamap explicitly and b) include all maps including the US.

Perhaps that already does the trick for you and if not I'm happy to take in pull requests. I wouldn't mind either however if you created a new repository using MeteorPackaging - that might very well be a better setup.

**Comment by jdlubrano** [comment]
@hyperborea,

I greatly appreciate your updates to the package; that was especially generous of you...it would be nice to get the same level of support from all open-source efforts!  I haven't gotten to try the new package out yet, but it looks like your changes should do the trick in the short-term.

I think that the best, long-term solution would be to update your repo to follow the pattern specified by [Meteor Autopublish](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Wrapping-3rd-Party-Packages).  That way we can eliminate the need for anyone to manually run `meteor publish` every time the Datamaps library itself is updated.  I have done this for another package already, so I plan to submit a PR hopefully this weekend.

Once we have the autopublish changes in place, we can contact the Meteor Packaging folks and transfer this repo to the Meteor Packaging Github organization.  That should also be enough to get yourself added to the organization (if you are not already).

Does that sound agreeable to you?
